// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prove.Data.Data;

namespace Prove.Data.Data.Migrations.ProveExtMigrations
{
    [DbContext(typeof(ProveExtContext))]
    [Migration("20220914055058_addtableactandupload")]
    partial class addtableactandupload
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Prove.Data.Dao.Prove.ActivityLog", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("ErrorMessage");

                    b.Property<string>("Info")
                        .HasMaxLength(400);

                    b.Property<string>("Method")
                        .HasMaxLength(40);

                    b.Property<string>("Remark")
                        .HasMaxLength(400);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("TrxId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("ActivityLog");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.FileUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BucketName");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100);

                    b.Property<string>("FileName");

                    b.Property<string>("FilePath");

                    b.Property<string>("Flag");

                    b.Property<string>("IsActive")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasMaxLength(1);

                    b.Property<long>("Length");

                    b.Property<string>("Remark");

                    b.Property<int>("TrxId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.ToTable("FileUpload");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.Glossary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100);

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("IsActive")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasMaxLength(1);

                    b.Property<string>("Reference")
                        .HasMaxLength(100);

                    b.Property<string>("Term")
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.ToTable("Glossary");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.Probis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChildProbisNumber");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100);

                    b.Property<string>("Description");

                    b.Property<string>("IsActive")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasMaxLength(1);

                    b.Property<string>("ParentProbisNumber")
                        .HasMaxLength(50);

                    b.Property<int>("Under_Parent");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.ToTable("Probis");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.ProductOfLawSKSP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100);

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<string>("IsActive")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasMaxLength(1);

                    b.Property<string>("KBO")
                        .HasMaxLength(10);

                    b.Property<string>("PositionNumber")
                        .HasMaxLength(10);

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.ToTable("ProductOfLawSKSP");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.ProductOfLawSTK", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100);

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<string>("IsActive")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasMaxLength(1);

                    b.Property<int?>("TypeId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("ProductOfLawSTK");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.RegulationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100);

                    b.Property<int>("FileId");

                    b.Property<int>("FileSupportId");

                    b.Property<string>("IsActive")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasMaxLength(1);

                    b.Property<string>("Notes");

                    b.Property<string>("Number");

                    b.Property<int?>("RegulationSKSPId");

                    b.Property<int?>("RegulationSTKId");

                    b.Property<string>("Status");

                    b.Property<string>("Title");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.HasIndex("RegulationSKSPId");

                    b.HasIndex("RegulationSTKId");

                    b.ToTable("RegulationHistory");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.RegulationSKSP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(5);

                    b.Property<string>("CompanyCode");

                    b.Property<string>("ConceptorDirId");

                    b.Property<string>("ConceptorDivId");

                    b.Property<string>("ConceptorId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ExpiredDate");

                    b.Property<int>("FileId");

                    b.Property<int>("FileSupportId");

                    b.Property<string>("IsActive")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasMaxLength(1);

                    b.Property<DateTime?>("JointReviewDate");

                    b.Property<string>("KBO")
                        .HasMaxLength(10);

                    b.Property<string>("Number")
                        .HasMaxLength(5);

                    b.Property<string>("PositionNumber")
                        .HasMaxLength(10);

                    b.Property<int?>("ProductOfLawSKSPId");

                    b.Property<int>("RegCategoryId");

                    b.Property<string>("SKSPNumber")
                        .HasMaxLength(50);

                    b.Property<int?>("SaveCodeId");

                    b.Property<string>("Status");

                    b.Property<int>("StatusDocId");

                    b.Property<string>("Title");

                    b.Property<DateTime>("TmtApplies");

                    b.Property<int>("TypeId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(400);

                    b.Property<string>("Year")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.HasIndex("ProductOfLawSKSPId");

                    b.HasIndex("SaveCodeId");

                    b.ToTable("RegulationSKSP");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.RegulationSTK", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode");

                    b.Property<string>("ConceptorDirId");

                    b.Property<string>("ConceptorDivId");

                    b.Property<string>("ConceptorId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ExpiredDate");

                    b.Property<int>("FileId");

                    b.Property<int>("FileSupportId");

                    b.Property<string>("IsActive")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasMaxLength(1);

                    b.Property<DateTime?>("JointReviewDate");

                    b.Property<string>("KBO")
                        .HasMaxLength(10);

                    b.Property<string>("Number")
                        .HasMaxLength(8);

                    b.Property<string>("PositionCode")
                        .HasMaxLength(10);

                    b.Property<string>("PositionId")
                        .HasMaxLength(10);

                    b.Property<int?>("ProbisId");

                    b.Property<string>("ProbisNumber")
                        .HasMaxLength(2);

                    b.Property<int?>("ProductOfLawSTKId");

                    b.Property<string>("RefNumber")
                        .HasMaxLength(50);

                    b.Property<int>("RegCategoryId");

                    b.Property<int>("RevisedFlag");

                    b.Property<string>("STKNumber")
                        .HasMaxLength(100);

                    b.Property<int?>("SaveCodeId");

                    b.Property<string>("SerialNumberSTK")
                        .HasMaxLength(8);

                    b.Property<string>("Status");

                    b.Property<int>("StatusDocId");

                    b.Property<string>("Title");

                    b.Property<DateTime>("TmtApplies");

                    b.Property<int?>("TypeId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(400);

                    b.Property<string>("Year")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.HasIndex("ProbisId");

                    b.HasIndex("ProductOfLawSTKId");

                    b.HasIndex("SaveCodeId");

                    b.HasIndex("TypeId");

                    b.ToTable("RegulationSTK");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.STKType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(1);

                    b.HasKey("Id");

                    b.ToTable("STKType");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.SaveCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(5);

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("SaveCode");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100);

                    b.Property<int>("FileId");

                    b.Property<string>("FileName");

                    b.Property<string>("FileType");

                    b.Property<string>("IsActive")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasMaxLength(1);

                    b.Property<int?>("TypeId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Template");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.TemplateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("TemplateType");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCode");

                    b.Property<string>("CompanyName");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100);

                    b.Property<string>("Email");

                    b.Property<string>("IdamanId");

                    b.Property<string>("IsActive")
                        .HasMaxLength(1);

                    b.Property<string>("IsDeleted")
                        .HasMaxLength(1);

                    b.Property<string>("Name");

                    b.Property<string>("OrganizationId");

                    b.Property<string>("OrganizationName");

                    b.Property<string>("OrganizationParentId");

                    b.Property<string>("OrganizationParentName");

                    b.Property<string>("PositionId");

                    b.Property<string>("PositionName");

                    b.Property<string>("PositionParentId");

                    b.Property<string>("PositionParentName");

                    b.Property<string>("Role");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(400);

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.ProductOfLawSTK", b =>
                {
                    b.HasOne("Prove.Data.Dao.Prove.STKType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.RegulationHistory", b =>
                {
                    b.HasOne("Prove.Data.Dao.Prove.RegulationSKSP", "RegulationSKSP")
                        .WithMany()
                        .HasForeignKey("RegulationSKSPId");

                    b.HasOne("Prove.Data.Dao.Prove.RegulationSTK", "RegulationSTK")
                        .WithMany()
                        .HasForeignKey("RegulationSTKId");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.RegulationSKSP", b =>
                {
                    b.HasOne("Prove.Data.Dao.Prove.ProductOfLawSKSP", "ProductOfLawSKSP")
                        .WithMany()
                        .HasForeignKey("ProductOfLawSKSPId");

                    b.HasOne("Prove.Data.Dao.Prove.SaveCode", "SaveCode")
                        .WithMany()
                        .HasForeignKey("SaveCodeId");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.RegulationSTK", b =>
                {
                    b.HasOne("Prove.Data.Dao.Prove.Probis", "Probis")
                        .WithMany()
                        .HasForeignKey("ProbisId");

                    b.HasOne("Prove.Data.Dao.Prove.ProductOfLawSTK", "ProductOfLawSTK")
                        .WithMany()
                        .HasForeignKey("ProductOfLawSTKId");

                    b.HasOne("Prove.Data.Dao.Prove.SaveCode", "SaveCode")
                        .WithMany()
                        .HasForeignKey("SaveCodeId");

                    b.HasOne("Prove.Data.Dao.Prove.STKType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");
                });

            modelBuilder.Entity("Prove.Data.Dao.Prove.Template", b =>
                {
                    b.HasOne("Prove.Data.Dao.Prove.TemplateType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
